name: My first Github actions
on: [push]
jobs:
        build-job:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - run: tree 


